### ISSUE TITLE
update for inventory2.0

### ISSUE THREAD

**Issue by phantomora** [DarrenJDocherty/RedM-Grave-Robbing#2]
need help fixing the error:
SCRIPT ERROR: @RedM-Grave-Robbing/server.lua:21: attempt to call a nil value (field 'addItem')
> ref (@RedM-Grave-Robbing/server.lua:21)
> handler (@redem_roleplay/server/sv_main.lua:76)
> handler (@RedM-Grave-Robbing/server.lua:18)

**Comment by DarrenJDocherty** [comment]
Are you using version 1.0 or 2.0 of redemrp_inventory? 

If 2.0, I believe the function is now AddItem (note the capital 'A') rather than addItem. I have not yet used the new version so I'm unsure if there are other prerequisites required.

Edit: just notice the issues subject header. Please try the above fix for 2.0 and let me know if it works.

**Comment by phantomora** [comment]
no it didnt work same error
SCRIPT ERROR: @RedM-Grave-Robbing/server.lua:21: attempt to call a nil value (field 'AddItem')
> ref (@RedM-Grave-Robbing/server.lua:21)
> handler (@redem_roleplay/server/sv_main.lua:76)
> handler (@RedM-Grave-Robbing/server.lua:18)

ill look at some other mods that i had to tweek to get them to work with inventory2.0 and see what ive missed

**Comment by phantomora** [comment]
well i was able to get it to 
SCRIPT ERROR: @RedM-Grave-Robbing/server.lua:21: attempt to call a nil value (field 'AddItem')
> handler (@redem_roleplay/server/sv_main.lua:76)
> handler (@RedM-Grave-Robbing/server.lua:18)
but still having the error.
heres whave ive done so far.
[server.txt](https://github.com/DarrenJDocherty/RedM-Grave-Robbing/files/5673413/server.txt)

**Comment by phantomora** [comment]
i just got it to work.
